apiVersion: apps/v1
kind: Deployment
metadata:
  name: dsu-bookstore
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bookstore
  template:
    metadata:
      labels:
        app: bookstore
    spec:
      containers:
      - name: bookstore-cont
        image: kondavenkat035/dsc_bookstore:latest
        ports:
        - containerPort: 8080
